# Generated by Django 3.1 on 2020-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_profile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
