# Generated by Django 3.1 on 2020-08-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='consumption',
            field=models.IntegerField(default=0),
        ),
    ]
